const supported=['en','es','fr','de','it','pt','ja'],original=new Map();
function set(s,v,h=false){const e=document.querySelector(s);if(!e)throw Error(s);if(!original.has(e))original.set(e,e.innerHTML);if(h){e.replaceChildren(document.createTextNode(v[0]),document.createElement('br'));const em=document.createElement('em');em.textContent=v[1];e.append(em);}else e.textContent=v;}
function list(s,v){document.querySelectorAll(s).forEach((e,i)=>{if(v[i]===undefined)throw Error(s);if(!original.has(e))original.set(e,e.innerHTML);e.textContent=v[i];});}
const label=document.createElement('label');label.className='language-picker';const labelText=document.createElement('span'),select=document.createElement('select');select.id='language';label.append(labelText,select);document.querySelector('header').append(label);select.append(new Option('Automatic (browser)','auto'));Object.entries({en:'English',es:'Español',fr:'Français',de:'Deutsch',it:'Italiano',pt:'Português',ja:'日本語'}).forEach(([k,v])=>select.append(new Option(v,k)));
const title=document.title,description=document.querySelector('meta[name="description"]').content,alt=document.querySelector('.screen-stage img').alt;
function browserLanguage(){for(const l of navigator.languages||[navigator.language]){const c=String(l).toLowerCase().split(/[-_]/)[0];if(supported.includes(c))return c;}return 'en';}
function apply(choice){const lang=choice==='auto'?browserLanguage():choice;for(const[e,h]of original)e.innerHTML=h;document.documentElement.lang=lang;document.title=title;document.querySelector('meta[name="description"]').content=description;document.querySelector('.screen-stage img').alt=alt;select.value=choice;labelText.textContent='Language';select.options[0].textContent='Automatic (browser)';if(lang==='en')return;const t=window.WO_TRANSLATIONS[lang];labelText.textContent=t.language;select.options[0].textContent=t.auto;
list('header nav a',t.nav);set('.brand small','Bitter Softworks');set('.hero .eyebrow',t.hero[0]);set('h1',t.hero.slice(1,3),true);set('.hero .intro',t.hero[3]+' '+t.hero[4]);list('.hero .actions a',t.hero.slice(5,7));set('.release',t.hero[7]);set('.hero-note span',t.hero[8]);set('.hero-note p',t.hero[9]);list('.ribbon span',[...t.ribbon,'WHAT’S OUT']);
set('#discover .eyebrow',t.discover[0]);set('#discover h2',t.discover.slice(1,3),true);set('#discover .section-intro',t.discover[3]);list('#discover .feature h3',[t.discover[4],t.discover[6],t.discover[8]]);list('#discover .feature p',[t.discover[5],t.discover[7],t.discover[9]]);set('.orbit-label',t.discover[10]);set('figcaption',t.discover[11]);document.querySelector('.screen-stage img').alt=t.alt;
set('#business .eyebrow',t.business[0]);set('#business h2',t.business.slice(1,3),true);set('.business-content > p:first-child',t.business[3]);set('.business-content > p:nth-child(2)',t.business[4]);list('.business-grid h3',[t.business[5],t.business[7],t.business[9],t.business[11]]);list('.business-grid p',[t.business[6],t.business[8],t.business[10],t.business[12]]);set('.business-content > a',t.business[13]);set('.business-content > .small',t.business[14]);
set('#support-feature .eyebrow',t.support[0]);set('#support-feature h2',t.support.slice(1,3),true);set('#support-feature strong',t.support[3]);set('#support-feature > p:last-child',t.support[4]+' '+t.support[5]);set('.invitation:not(#support-feature) .eyebrow',t.invite[0]);set('.invitation:not(#support-feature) h2',t.invite.slice(1,3),true);set('.invitation:not(#support-feature) > p:last-child',t.invite[3]+' '+t.invite[4]);
set('.questions .eyebrow',t.faq[0]);set('.questions h2',t.faq.slice(1,3),true);list('.questions summary',[t.faq[3],t.faq[5],t.faq[7],t.faq[9],t.faq[11]]);list('.questions details p',[t.faq[4],t.faq[6],t.faq[8],t.faq[10],t.faq[12]]);set('#launch .eyebrow',t.launch[0]);set('#launch h2',t.launch.slice(1,3),true);set('#launch > p:nth-of-type(2)',t.launch[3]);list('#launch .actions a',t.launch.slice(4,6));set('#launch .small',t.launch[6]);set('footer > p',t.footer[0]+' · '+t.footer[1]);set('footer div a:last-child',t.footer[2]);document.title=`What’s Out — ${t.hero[2]}`;document.querySelector('meta[name="description"]').content=t.hero[4]+' '+t.launch[3];}
let preference='auto';try{const s=localStorage.getItem('whatsout-language');if(s==='auto'||supported.includes(s))preference=s;}catch{}apply(preference);select.addEventListener('change',()=>{preference=select.value;try{localStorage.setItem('whatsout-language',preference);}catch{}apply(preference);});window.addEventListener('languagechange',()=>{if(preference==='auto')apply('auto');});
